let sb=null;const $=id=>document.getElementById(id);const status=(id,t)=>$(id).textContent=t;
function configured(){return window.supabase&&window.SUPABASE_URL&&!window.SUPABASE_URL.startsWith('YOUR_')&&window.SUPABASE_PUBLISHABLE_KEY&&!window.SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_')}
async function boot(){if(!configured()){status('loginStatus','First configure supabase-config.js with your Project URL and Publishable key.');return}sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);const {data:{session}}=await sb.auth.getSession();if(session)showPanel()}
$('loginBtn').onclick=async()=>{if(!configured())return status('loginStatus','Supabase is not configured yet.');const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return status('loginStatus','Login failed: '+error.message);showPanel()};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function showPanel(){ $('loginCard').hidden=true;$('panel').hidden=false;loadStatus() }
$('publishBtn').onclick=async()=>{const f=$('excel').files[0],month=$('month').value.trim();if(!f||!month)return status('publishStatus','Select an Excel file and enter the month label.');try{status('publishStatus','Reading Excel…');const buf=await f.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null});let header=-1,map={};for(let i=0;i<Math.min(rows.length,30);i++){const r=rows[i].map(v=>String(v??'').trim().toLowerCase());if(r.includes('model')&&r.includes('variant')&&r.includes('incentive')){header=i;r.forEach((v,j)=>map[v]=j);break}}if(header<0)throw Error('Could not find Model / Variant / Incentive columns.');let model='',items=[];for(const r of rows.slice(header+1)){if(r[map.model]!=null&&String(r[map.model]).trim())model=String(r[map.model]).trim();const variant=r[map.variant]!=null?String(r[map.variant]).trim():'';if(!variant)continue;const num=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};items.push({model,variant,incentive:num(r[map.incentive]),spot1:num(r[map['spot 1']]),spot2:num(r[map['spot 2']])})}if(!items.length)throw Error('No variant rows found.');status('publishStatus',`Publishing ${items.length} variants…`);const {data:id,error}=await sb.rpc('publish_incentive_scheme',{p_month:month,p_items:items});if(error)throw error;status('publishStatus',`✅ Published ${month}\n${items.length} variants\nScheme ID: ${id}`);loadStatus()}catch(e){status('publishStatus','Error: '+e.message)}};
$('announceBtn').onclick=async()=>{try{const title=$('aTitle').value.trim(),message=$('aMessage').value.trim();if(!title)throw Error('Enter a title.');const starts_at=$('aStart').value?new Date($('aStart').value).toISOString():new Date().toISOString();const ends_at=$('aEnd').value?new Date($('aEnd').value).toISOString():null;const {error}=await sb.from('announcements').insert({title,message,image_url:$('aImage').value.trim()||null,starts_at,ends_at,display_frequency:$('aFreq').value,is_active:true});if(error)throw error;status('announceStatus','✅ Announcement published.');loadStatus()}catch(e){status('announceStatus','Error: '+e.message)}};
async function loadStatus(){const {data:s,error:se}=await sb.from('incentive_schemes').select('month_label,published_at').eq('is_published',true).order('published_at',{ascending:false}).limit(1).maybeSingle();const {data:a,error:ae}=await sb.from('announcements').select('title,is_active,starts_at,ends_at').order('created_at',{ascending:false}).limit(10);if(se||ae){$('currentStatus').textContent='Unable to load status. Check your admin role and Supabase policies.';return}$('currentStatus').textContent=`Published scheme: ${s?.month_label||'None'}\nPublished: ${s?.published_at?new Date(s.published_at).toLocaleString('en-IN'):'—'}\n\nRecent announcements:\n${(a||[]).map(x=>`• ${x.title} — ${x.is_active?'enabled':'disabled'}`).join('\n')||'None'}`}
boot();