const $ = id => document.getElementById(id);
const money = n => '₹' + Number(n || 0).toLocaleString('en-IN');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

let INCENTIVES_LOCAL = Array.isArray(window.INCENTIVES) ? window.INCENTIVES : INCENTIVES;
const state = { sales: [], announcements: [], qualification: null, qualificationLoading: false };
const model = $('model'), variant = $('variant'), bookingDate = $('bookingDate');

const OCT_SCHEME = {
  period(date) {
    return date.getDate() <= 10
      ? { name:'PRE-NAVRATRI BONANZA', range:'1–10 October 2026', short:'PRE-NAVRATRI • 1–10 OCT', booking:[0,1500,3000,5000,1500] }
      : { name:'NAVRATRI BOOKING BONANZA', range:'11–31 October 2026', short:'NAVRATRI • 11–31 OCT', booking:[0,750,1500,2500,750] };
  },
  models: {
    'NEW BALENO': { cng:[500,750,1000,1500], petrol:[1250,1500,2500,3000] },
    'Fronx': { cng:[500,750,1000,1500], petrol:[1250,1500,2500,3000], turbo:[5000] },
    'XL6': { all:[3000] },
    'JIMNY': { all:[5000] },
    'INVICTO': { all:[10000] },
    'E-VITARA': { all:[7000] }
  },
  exchange: { 'NEW BALENO':750, 'Fronx':500, 'XL6':1000, 'JIMNY':1000, 'INVICTO':3000, 'E-VITARA':2500 },
  ew: 300,
  gna: [[40000,50000,1200],[50000,60000,2000],[60000,Infinity,4000]],
  gvStep: { petrol:[5000,6000], cng:[2000,3000] },
  gvHigh: 4000,
  gvStrongHybrid: 5000,
  minCars: 4,
  zeroGVReduction: .25
};

function selectedPeriod(){ const d = new Date(`${bookingDate.value || '2026-10-01'}T12:00:00`); return OCT_SCHEME.period(d); }
function updateSchemeUI(){ const s = selectedPeriod(); $('schemeBadge').innerHTML = `${s.name}<span>${s.range}</span>`; $('promoPeriod').textContent = s.short; $('monthPill').textContent = 'October 2026'; }
function fuelType(x){ const v=(x.variant||'').toUpperCase(); if(x.model==='NEW BALENO'||x.model==='Fronx'||x.model==='GRAND VITARA') return v.includes('CNG')?'cng':(v.includes('TURBO')?'turbo':'petrol'); return 'all'; }
function groupKey(x){ if(x.model==='NEW BALENO') return `NEW BALENO-${fuelType(x)}`; if(x.model==='Fronx') return `Fronx-${fuelType(x)}`; return x.model; }
function groupCount(x){ return state.sales.filter(s=>groupKey(s)===groupKey(x)).length; }
function gvCount(){ return state.sales.filter(s=>s.model==='GRAND VITARA').length; }
function isGVHigh(x){ if(x.model!=='GRAND VITARA') return false; const v=(x.variant||'').toUpperCase(); return /ZETA|ALPHA|DELTA\+/.test(v) && !v.includes('SIGMA'); }
function isGVStrongHybrid(x){ return x.model==='GRAND VITARA' && /STRONG HYBRID|STRONGHYBRID|HYBRID/.test((x.variant||'').toUpperCase()); }
function modelIncentive(x){ const rule=OCT_SCHEME.models[x.model]; if(!rule) return Number(x.main||0); const arr=rule[fuelType(x)]||rule.all||[0]; const n=groupCount(x)+1; return arr[Math.min(n-1,arr.length-1)]||0; }
function gvStep(x){ if(x.model!=='GRAND VITARA') return 0; const arr=OCT_SCHEME.gvStep[fuelType(x)]||OCT_SCHEME.gvStep.petrol; return arr[Math.min(gvCount(),1)]||0; }
function exchangeBonus(x){ return OCT_SCHEME.exchange[x.model]||0; }
function gnaBonus(value){ const n=Number(value||0); const row=OCT_SCHEME.gna.find(r=>n>=r[0]&&n<r[1]); return row?row[2]:0; }
function bookingBonus(count){ const a=selectedPeriod().booking; if(count<2)return 0; if(count>=5)return count*a[4]; return a[count-1]||0; }
function vehicleCalc(x){ const base=modelIncentive(x); const step=gvStep(x)+(isGVHigh(x)?OCT_SCHEME.gvHigh:0)+(isGVStrongHybrid(x)?OCT_SCHEME.gvStrongHybrid:0); const ex=x.exchange?exchangeBonus(x):0; const ew=x.ew?OCT_SCHEME.ew:0; const gna=x.gnaValue?gnaBonus(x.gnaValue):0; return {base,step,ex,ew,gna,total:base+step+ex+ew+gna}; }
function grossTotals(){ let modelTotal=0,stepTotal=0,allied=0; state.sales.forEach(x=>{const c=vehicleCalc(x);modelTotal+=c.base;stepTotal+=c.step;allied+=c.ex+c.ew+c.gna;}); const booking=bookingBonus(state.sales.length); return {modelTotal,stepTotal,allied,booking,gross:modelTotal+stepTotal+allied+booking}; }
function qualificationState(){ const m=$('mspin').value.trim(),el=$('qualStatus'); if(!m){state.qualification=null;el.className='qual-status';el.innerHTML='<span>●</span><div><b>Enter MSPIN</b><small>Qualification will be checked from the published October Target vs Achievement data.</small></div>';return;} if(state.qualificationLoading){el.className='qual-status';el.innerHTML='<span>●</span><div><b>Checking MSPIN…</b><small>Matching the October RM master data.</small></div>';return;} if(!state.qualification){el.className='qual-status';el.innerHTML='<span>●</span><div><b>MSPIN captured</b><small>No October record found yet. Publish the Target vs Achievement master file to validate.</small></div>';return;} const q=state.qualification,pct=q.target>0?q.achievement/q.target*100:Number(q.achievementPct||0),targetOk=q.target>0&&pct>=100,carsOk=state.sales.length>=OCT_SCHEME.minCars,eligible=targetOk&&carsOk,deduction=eligible&&gvCount()===0;el.className='qual-status '+(eligible?'good':'warn');el.innerHTML=`<span>${eligible?'✓':'!'}</span><div><b>${eligible?'QUALIFIED':'NOT YET QUALIFIED'}</b><small>Target vs Ach: ${pct.toFixed(0)}% • ${state.sales.length}/${OCT_SCHEME.minCars} cars • GV: ${gvCount()} ${deduction?'• 25% deduction':''}</small></div>`; }
async function lookupQualification(){ const m=$('mspin').value.trim(); if(!m||!window.supabase||!window.SUPABASE_URL||window.SUPABASE_URL.startsWith('YOUR_')){qualificationState();return;} state.qualificationLoading=true;qualificationState();try{const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);const {data,error}=await sb.from('rm_qualification').select('mspin,target,achievement,achievement_pct,gv_retail,month_label').eq('mspin',m).eq('is_published',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;state.qualification=data||null;}catch(e){console.warn('Qualification lookup unavailable:',e);state.qualification=null;}state.qualificationLoading=false;qualificationState();render(); }
function renderTiers(){ const groups={};state.sales.forEach(x=>groups[groupKey(x)]=(groups[groupKey(x)]||0)+1);$('scheme').hidden=false;$('tiers').innerHTML=Object.entries(groups).map(([k,n])=>`<div class="tier active"><small>${esc(k.replace('NEW BALENO-','Baleno ').replace('Fronx-','Fronx '))} • ${n} car${n>1?'s':''}</small><b>${money(state.sales.filter(x=>groupKey(x)===k).reduce((a,x)=>{const c=vehicleCalc(x);return a+c.base+c.step},0))}</b></div>`).join('')||`<div class="tier"><small>Booking period</small><b>${esc(selectedPeriod().short)}</b></div>`;$('nextMilestone').textContent=state.sales.length<4?`${4-state.sales.length} car${4-state.sales.length===1?'':'s'} to qualify`:money(bookingBonus(state.sales.length+1)-bookingBonus(state.sales.length)); }
function render(){ const t=grossTotals(),q=state.qualification,targetOk=q&&q.target>0&&(q.achievement/q.target*100)>=100,carsOk=state.sales.length>=OCT_SCHEME.minCars,qualified=!!q&&targetOk&&carsOk,deduction=qualified&&gvCount()===0,finalTotal=qualified?Math.round(t.gross*(deduction?.75:1)):t.gross;$('grandTotal').textContent=money(finalTotal);$('headTotal').textContent=money(finalTotal);$('vehicleCount').textContent=state.sales.length;$('countText').textContent=`${state.sales.length} ${state.sales.length===1?'vehicle':'vehicles'}`;$('statusText').textContent=!q?'POTENTIAL / VERIFY':qualified?(deduction?'25% DEDUCTION':'QUALIFIED'):'NOT QUALIFIED';$('sumMain').textContent=money(t.modelTotal);$('sumStep').textContent=money(t.stepTotal+t.booking);$('sumAllied').textContent=money(t.allied);$('sumTotal').textContent=money(finalTotal);$('emptyTable').style.display=state.sales.length?'none':'block';$('summary').hidden=!state.sales.length;const dl=$('deductionLine');if(state.sales.length){if(!q){dl.hidden=false;dl.textContent='Qualification pending: enter MSPIN and publish the October Target vs Achievement master data.';}else if(!qualified){dl.hidden=false;dl.textContent=`Eligibility pending: ${targetOk?'minimum 4 vehicle condition not yet met':'100% Target vs Achievement condition not met'}. Gross potential is shown above until qualification is confirmed.`;}else if(deduction){dl.hidden=false;dl.textContent='25% deduction applied because the qualified opportunity has ZERO Grand Vitara retail.';}else dl.hidden=true;}renderTiers();$('salesBody').innerHTML=state.sales.map((x,i)=>{const c=vehicleCalc(x);return `<tr><td>${i+1}</td><td class="model-name">${esc(x.model)}</td><td class="variant-name">${esc(x.variant)}</td><td>${x.exchange?'Yes':'No'}</td><td>${x.ew?'Yes':'No'}</td><td>${x.gnaValue?money(x.gnaValue):'₹0'}</td><td>${money(c.base+c.ex+c.ew+c.gna)}</td><td class="step">${money(c.step)}</td><td>${money(c.total)}</td><td><button class="delete" data-id="${x.id}">×</button></td></tr>`}).join('');document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>removeSale(b.dataset.id));qualificationState(); }
function renderPreview(x){ if(!x){$('preview').hidden=true;return;}const g=gnaBonus($('gna').value),ex=$('exchange').value==='Yes'?exchangeBonus(x):0,ew=$('ew').value==='Yes'?OCT_SCHEME.ew:0,temp={...x,exchange:$('exchange').value==='Yes',ew:$('ew').value==='Yes',gnaValue:Number($('gna').value||0)},c=vehicleCalc(temp);$('preview').innerHTML=`<span>Model <b>${money(c.base)}</b></span><span>GV/Step-Up <b>${money(c.step)}</b></span><span>Exchange <b>${money(ex)}</b></span><span>EW <b>${money(ew)}</b></span><span>GNA <b>${money(g)}</b></span>`;$('preview').hidden=false; }
function renderModelVisual(m){const el=$('modelVisual');if(!m){el.innerHTML='<div class="visual-placeholder"><span>SELECT A MODEL</span><b>Vehicle preview</b></div>';return;}const src=({'NEW BALENO':'vehicle-images/Baleno.png','Old BALENO':'vehicle-images/Baleno.png','Fronx':'vehicle-images/Fronx.png','GRAND VITARA':'vehicle-images/GrandVitara.png','XL6':'vehicle-images/XL6.png','INVICTO':'vehicle-images/Invicto.png','JIMNY':'vehicle-images/Jimny.png','E-VITARA':'vehicle-images/eVitara.png'})[m];el.innerHTML=src?`<div class="vehicle-photo"><img src="${src}" alt="${esc(m)} vehicle"><div class="vehicle-photo-overlay"><strong>${esc(m)}</strong><small>Model selected</small></div></div>`:`<div class="vehicle-art"><div class="vehicle-shape"></div><div class="vehicle-label">${esc(m)}</div><small>Model selected</small></div>`;}
function resetSelector(){model.value='';variant.innerHTML='<option value="">Select variant</option>';variant.disabled=true;$('addBtn').disabled=true;$('preview').hidden=true;$('exchange').value='No';$('ew').value='No';$('gna').value='0';renderModelVisual('');}
function removeSale(id){state.sales=state.sales.filter(x=>x.id!==id);render();}
async function loadMaster(){if(!window.supabase||!window.SUPABASE_URL||window.SUPABASE_URL.startsWith('YOUR_')){init();showAnnouncement();return;}const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);try{const {data:s,error:se}=await sb.from('incentive_schemes').select('id,month_label,is_published,step_up_enabled,step_up_tiers').eq('is_published',true).order('published_at',{ascending:false}).limit(1).maybeSingle();if(se)throw se;if(s){const {data:items,error:ie}=await sb.from('incentive_items').select('model,variant,incentive,spot1,spot2,main_incentives,spot_incentives').eq('scheme_id',s.id);if(!ie&&items?.length)INCENTIVES_LOCAL=items.map(x=>({...x,main:Number(x.incentive||x.main||0)}));}}catch(e){console.warn('Published model data unavailable; October RM scheme remains active.',e)}try{const {data:a,error:ae}=await sb.from('announcements').select('*').eq('is_active',true).order('created_at',{ascending:false});if(!ae)state.announcements=a||[]}catch(e){state.announcements=[]}init();showAnnouncement();}
function init(){updateSchemeUI();model.innerHTML='<option value="">Select model</option>';[...new Set(INCENTIVES_LOCAL.map(x=>x.model))].forEach(m=>{const o=document.createElement('option');o.value=m;o.textContent=m;model.appendChild(o)});render();}
model.onchange=()=>{variant.innerHTML='<option value="">Select variant</option>';variant.disabled=!model.value;$('addBtn').disabled=true;if(model.value)INCENTIVES_LOCAL.filter(x=>x.model===model.value).forEach(x=>{const o=document.createElement('option');o.value=x.variant;o.textContent=x.variant;variant.appendChild(o)});renderModelVisual(model.value);renderPreview(INCENTIVES_LOCAL.find(x=>x.model===model.value&&x.variant===variant.value));};
variant.onchange=()=>{const x=INCENTIVES_LOCAL.find(x=>x.model===model.value&&x.variant===variant.value);$('addBtn').disabled=!x;renderPreview(x);};
['exchange','ew','gna'].forEach(id=>$(id).onchange=()=>renderPreview(INCENTIVES_LOCAL.find(x=>x.model===model.value&&x.variant===variant.value)));
bookingDate.onchange=()=>{updateSchemeUI();render();};
let mspinTimer;$('mspin').oninput=()=>{clearTimeout(mspinTimer);state.qualification=null;qualificationState();mspinTimer=setTimeout(lookupQualification,450)};
$('addBtn').onclick=()=>{const x=INCENTIVES_LOCAL.find(x=>x.model===model.value&&x.variant===variant.value);if(!x)return;state.sales.push({...x,exchange:$('exchange').value==='Yes',ew:$('ew').value==='Yes',gnaValue:Number($('gna').value||0),id:String(Date.now()+Math.random())});resetSelector();render();};
$('resetBtn').onclick=()=>{if(!state.sales.length||confirm('Clear all vehicles from this opportunity?')){state.sales=[];resetSelector();render();}};
function showAnnouncement(){return;}
loadMaster();