/* October 2026 RM calculator vehicle master.
   Exposed on window because app.js reads window.INCENTIVES. */
window.INCENTIVES = [
  ...[
    'NEW BALENO SIGMA 1.2 5MT','NEW BALENO DELTA 1.2 5MT','NEW BALENO ZETA 1.2 5MT','NEW BALENO ALPHA 1.2 5MT','NEW BALENO ALPHA (O) 1.2 5MT','NEW BALENO DELTA 1.2 AGS','NEW BALENO ZETA 1.2 AGS','NEW BALENO ALPHA 1.2 AGS','NEW BALENO ALPHA (O) 1.2 AGS','NEW BALENO DELTA CNG 1.2 5MT','NEW BALENO ZETA CNG 1.2 5MT'
  ].map(variant => ({ model: 'NEW BALENO', variant })),
  ...[
    'FRONX SIGMA 1.2L 5MT','FRONX DELTA 1.2L 5MT','FRONX DELTA+ 1.2L 5MT','FRONX DELTA 1.2L AGS','FRONX DELTA+ 1.2L AGS','FRONX TURBO DELTA+ 1.0L 5MT','FRONX TURBO ZETA 1.0L 5MT','FRONX TURBO ALPHA 1.0L 5MT','FRONX TURBO ZETA 1.0L 6AT','FRONX TURBO ALPHA 1.0L 6AT','FRONX SIGMA CNG 1.2L 5MT','FRONX DELTA CNG 1.2L 5MT'
  ].map(variant => ({ model: 'Fronx', variant })),
  ...[
    'GRAND VITARA SIGMA 1.5L 5MT','GRAND VITARA DELTA 1.5L 5MT','GRAND VITARA ZETA 1.5L 5MT','GRAND VITARA ALPHA 1.5L 5MT','GRAND VITARA DELTA 1.5L 6AT','GRAND VITARA ZETA 1.5L 6AT','GRAND VITARA ALPHA 1.5L 6AT','GRAND VITARA ALPHA4WD 1.5L 6AT','GRAND VITARA ZETA (O) 1.5L 5MT','GRAND VITARA ZETA (O) 1.5L 6AT','GRAND VITARA ALPHA (O) 1.5L 5MT','GRAND VITARA ALPHA (O) 1.5L 6AT','GRAND VITARA ALPHA (O) ALLGRIP 1.5L 6AT','GRAND VITARA DELTA+ 1.5L CVT','GRAND VITARA ZETA+ 1.5L CVT','GRAND VITARA ALPHA+ 1.5L CVT','GRAND VITARA ZETA+ (O) 1.5L CVT','GRAND VITARA ALPHA+ (O) 1.5L CVT','GRAND VITARA DELTA CNG 1.5L 5MT','GRAND VITARA ZETA CNG 1.5L 5MT'
  ].map(variant => ({ model: 'GRAND VITARA', variant })),
  ...[
    'XL6 ZETA 1.5L 5MT','XL6 ZETA CNG 1.5L 5MT','XL6 ALPHA 1.5L 5MT','XL6 ALPHA+ 1.5L 6AT'
  ].map(variant => ({ model: 'XL6', variant })),
  ...[
    'JIMNY ZETA 1.5L 5MT','JIMNY ALPHA 1.5L 5MT','JIMNY ZETA 1.5L 4AT','JIMNY ALPHA 1.5L 4AT'
  ].map(variant => ({ model: 'JIMNY', variant })),
  ...[
    'INVICTO ZETA+ 2.0L CVT 7 STR','INVICTO ALPHA+ 2.0L CVT 7 STR'
  ].map(variant => ({ model: 'INVICTO', variant })),
  ...[
    'eVitara DELTA','eVitara ZETA','eVitara ALPHA'
  ].map(variant => ({ model: 'E-VITARA', variant }))
];
